#!/usr/bin/env bash

benchmark=$1
cg_android=callgraphs/spark-android-call-graphs/${benchmark}/android.txt.gzip
cg_android_averroes=callgraphs/spark-android-averroes-call-graphs/${benchmark}/androidAverroes.txt.gzip

echo -n "${benchmark} ... "

# diff call graphs
./cgdiff ${cg_android} ${cg_android_averroes}

# success
echo success