#! /usr/bin/env bash

set -e

benchmark=$1
props=averroes.properties
outputdir=callgraphs/spark-android-averroes-call-graphs/${benchmark}
apk=droidbench/${benchmark}.apk

echo "running Spark with Averroes for ${benchmark}"

# 0. create the averroes properties file
touch ${props}
echo "main_class = ca.uwaterloo.averroes.AndroidDummyMainClass" > ${props}
echo "android_path = android" >> ${props}
echo "output_dir = output" >> ${props}
echo "apk_location = ${apk}" >> ${props}
if test "${benchmark}" = "AndroidSpecific_Obfuscation1"; then
  echo "application_includes = ca.uwaterloo.averroes.AndroidDummyMainClass:de.ecspride.**:android.telephony.TelephonyManager" >> ${props}
else
  echo "application_includes = ca.uwaterloo.averroes.AndroidDummyMainClass:de.ecspride.**" >> ${props}
fi

# 1. make some dirs
mkdir -p ${outputdir}/

# 2. run spark-android-averroes.jar
jar uf spark-android-averroes.jar ${props}
java -verbose:gc -Xloggc:${outputdir}/${benchmark}-gc.stats -jar spark-android-averroes.jar $benchmark

# 3. copy the call graph
cp output/androidAverroes.txt.gzip ${outputdir}/androidAverroes.txt.gzip

echo ""