#! /usr/bin/env bash

set -e

# the droidbench programs
droidbench="droidbench-apks.txt"

function timing()
{
	echo "..."
	/usr/bin/time -f "elapsed time: %es" $* 2>&1
}

date
outputdir=benchmarks-averroes/android
mkdir -p ${outputdir}

while read benchmark
do
  echo "generating placeholder library for ${benchmark} ..."
  ./run-averroes-android ${benchmark} > ${outputdir}/${benchmark}.stats
done < ${droidbench}

date