#! /usr/bin/env bash

# the droidbench programs
droidbench="droidbench-apks.txt"

date

mkdir -p benchmarks-averroes/android

while read benchmark
do
  echo "running ${benchmark} ..."
  outputdir=callgraphs/spark-android-call-graphs/${benchmark}
  
  # 1. create output directory
  mkdir -p ${outputdir}/
  
  # 2. run the script
  ./spark-android ${benchmark} > ${outputdir}/${benchmark}-android.stats
done < ${droidbench}

date